version: '3'

services:

  openapi-nodejs:
    container_name: openapi-nodejs
    image: node:20.11.0-alpine3.19
    tty: true
    ports:
      - 3000:3000
    user: node
    working_dir: /usr/src/app
    command: /bin/sh -c "npm run dev"
    volumes:
      - ./app:/usr/src/app
    environment:
      DATABASE_URL: "postgresql://user:password@openapi-db:5432/openapi?schema=public"

  openapi-db:
    image: postgres:16.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.2
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin