/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /**
     * Hello, World!
     * @description Hello, World!
     */
    get: operations["GetHello"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Hello: {
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Hello, World!
   * @description Hello, World!
   */
  GetHello: {
    responses: {
      /** @description Hello */
      200: {
        content: {
          "application/json": components["schemas"]["Hello"];
        };
      };
    };
  };
}
